from baostock.data.resultset import ResultData

def query_stock_industry(code: str | None = ..., date: str | None = ...) -> ResultData: ...
def query_hs300_stocks(date: str | None = ...) -> ResultData: ...
def query_sz50_stocks(date: str | None = ...) -> ResultData: ...
def query_zz500_stocks(date: str | None = ...) -> ResultData: ...
def query_terminated_stocks(date: str | None = ...) -> ResultData: ...
def query_suspended_stocks(date: str | None = ...) -> ResultData: ...
def query_st_stocks(date: str | None = ...) -> ResultData: ...
def query_starst_stocks(date: str | None = ...) -> ResultData: ...
def query_stock_concept(code: str | None = ..., date: str | None = ...) -> ResultData: ...
def query_stock_area(code: str | None = ..., date: str | None = ...) -> ResultData: ...
def query_ame_stocks(date: str | None = ...) -> ResultData: ...
def query_gem_stocks(date: str | None = ...) -> ResultData: ...
def query_shhk_stocks(date: str | None = ...) -> ResultData: ...
def query_szhk_stocks(date: str | None = ...) -> ResultData: ...
def query_stocks_in_risk(date: str | None = ...) -> ResultData: ...
