"""
This type stub file was generated by pyright.
"""

import pandas as pd

"""
.. module:: utils
   :synopsis: Utils classes and functions.

.. moduleauthor:: Dario Lopez Padial (Bukosabino)

"""
class IndicatorMixin:
    """Util mixin indicator class"""
    _fillna = ...


def dropna(df: pd.DataFrame) -> pd.DataFrame:
    """Drop rows with "Nans" values"""
    ...

