"""
This type stub file was generated by pyright.
"""

"""
封装消息头
@author: baostock.com
@group : baostock.com
@contact: baostock@163.com
"""
def to_message_header(msg_type, total_msg_length):
    ...

