from baostock.data.resultset import ResultData

def query_trade_dates(start_date: str | None = ..., end_date: str | None = ...) -> ResultData: ...
def query_all_stock(day: str | None = ...) -> ResultData: ...
def query_stock_basic(code: str | None = ..., code_name: str | None = ...) -> ResultData: ...
