"""
This type stub file was generated by pyright.
"""

"""
获取默认socket
@author: baostock.com
@group : baostock.com
@contact: baostock@163.com
"""
class SocketUtil:
    """Socket工具类"""
    instance = ...
    init_flag = ...
    def __new__(cls, *args, **kwargs): # -> Self:
        ...
    
    def __init__(self) -> None:
        ...
    
    def connect(self): # -> None:
        """创建连接"""
        ...
    


def get_default_socket(): # -> socket | None:
    """获取默认连接"""
    ...

def send_msg(msg): # -> str | None:
    """发送消息，并接受消息 """
    ...

