"""
This type stub file was generated by pyright.
"""

"""
字符串方法
@author: baostock.com
@group : baostock.com
@contact: baostock@163.com
"""
def add_zero_for_string(content, length, direction): # -> str:
    """在str的左或右添加0
    :param str:待修改的字符串
    :param length:总共的长度
    :param direction:方向，True左，False右
    :return:
    """
    ...

def is_valid_date(str): # -> bool:
    """判断是否是一个有效的日期字符串
    :param str:
    :return: 符合格式返回True,
    """
    ...

def is_valid_year_date(str): # -> bool:
    """判断是否是一个有效的年日期字符串：yyyy
    :param str:
    :return: 符合格式返回True,
    """
    ...

def is_valid_year_month_date(str): # -> bool:
    """判断是否是一个有效的年月日期字符串：yyyy-mm
    :param str:
    :return: 符合格式返回True,
    """
    ...

def organize_msg_body(str): # -> LiteralString:
    """根据传入的信息，组织消息头，并返回"""
    ...

def organize_realtime_msg_body(str): # -> LiteralString:
    """根据传入的信息，组织消息头，并返回"""
    ...

