from baostock.data.resultset import ResultData

def query_performance_express_report(code: str, start_date: str = ..., end_date: str = ...) -> ResultData: ...
def query_forecast_report(code: str, start_date: str = ..., end_date: str = ...) -> ResultData: ...
