from baostock.data.resultset import ResultData

def query_deposit_rate_data(start_date: str | None = ..., end_date: str | None = ...) -> ResultData: ...
def query_loan_rate_data(start_date: str | None = ..., end_date: str | None = ...) -> ResultData: ...
def query_required_reserve_ratio_data(start_date: str | None = ..., end_date: str | None = ..., yearType: str = ...) -> ResultData: ...
def query_money_supply_data_month(start_date: str | None = ..., end_date: str | None = ...) -> ResultData: ...
def query_money_supply_data_year(start_date: str | None = ..., end_date: str | None = ...) -> ResultData: ...
def query_cpi_data(start_date: str | None = ..., end_date: str | None = ...) -> ResultData: ...
def query_ppi_data(start_date: str | None = ..., end_date: str | None = ...) -> ResultData: ...
def query_pmi_data(start_date: str | None = ..., end_date: str | None = ...) -> ResultData: ...
