import pandas as pd

def stock_balance_sheet_by_report_delisted_em(symbol: str = ...) -> pd.DataFrame: ...
def stock_profit_sheet_by_report_delisted_em(symbol: str = ...) -> pd.DataFrame: ...
def stock_cash_flow_sheet_by_report_delisted_em(symbol: str = ...) -> pd.DataFrame: ...
