from baostock.data.resultset import ResultData

def login(user_id: str = ..., password: str = ...) -> ResultData: ...
def set_API_key(apiKey: str = ...) -> None: ...
def logout(user_id: str = ...) -> ResultData: ...
